// Landscape Intelligence Network - Data
// 51 entries with full codification

const CATEGORIES = {
    "DT": { name: "Deep Time", color: "#003153" },
    "IE": { name: "Indigenous Epistemologies", color: "#1a4780" },
    "ES": { name: "Earth System Science", color: "#2e5984" },
    "CS": { name: "Cybernetics & Systems", color: "#4a7c9b" },
    "LA": { name: "Landscape Architecture", color: "#6b9eb8" },
    "CM": { name: "Critical Materials & Extraction", color: "#8fb9cf" },
    "EG": { name: "Environmental Governance", color: "#b3d4e5" },
    "CT": { name: "Contemporary Theory", color: "#d4e8f5" },
    "AC": { name: "Ancient & Classical", color: "#e8f4fc" }
};

const SOURCES = {
    "LI": { name: "Landscape Intelligence", color: "#6b9eb8" },
    "JACO": { name: "Jaco Challenge", color: "#8fb9cf" },
    "TA": { name: "Territorial Agency", color: "#4a7c9b" }
};

const SPHERE_INTERFACES = [
    "LITHO-GEO", "BIO-GEO", "BIO-ATMO", "BIO-BIO", "BIO-LITHO", 
    "ATMO-BIO", "ATMO-LITHO", "ATMO-TECHNO", "TECHNO-BIO", "TECHNO-GEO",
    "TECHNO-HYDRO", "TECHNO-LITHO", "TECHNO-TECHNO", "TECHNO-ATMO",
    "HYDRO-BIO", "HYDRO-TECHNO", "LITHO-TECHNO", "LITHO-BIO"
];

const ELEMENT_FUNCTIONS = [
    "ALL-CONCENTRATION", "ALL-DISPERSION", "ALL-CYCLING", "ALL-MOBILIZATION",
    "CARBON-CYCLING", "CARBON-SEQUESTRATION", "CARBON-SIGNALING", "CARBON-MOBILIZATION", "CARBON-DISPERSION", "CARBON-CONCENTRATION",
    "OXYGEN-CYCLING", "WATER-CYCLING", "WATER-MEMORY", "SOIL-MEMORY",
    "FIRE-CYCLING", "INFORMATION-MEMORY", "INFORMATION-SIGNALING", "INFORMATION-CYCLING",
    "INFORMATION-COORDINATION", "INFORMATION-MODELLING", "INFORMATION-DISPERSION",
    "ENERGY-SIGNALING", "ENERGY-CYCLING", "BIOTA-CYCLING", "BIOTA-DIVERSIFICATION",
    "NEODYMIUM-MOBILIZATION"
];

const INDETERMINACY_POSITIONS = {
    "CLEAR-COHERENT": { value: 5, label: "Clear Coherent", color: "#003153" },
    "SEARCH-PROMISING": { value: 4, label: "Search Promising", color: "#2e5984" },
    "PHASE-TRANSITION": { value: 3, label: "Phase Transition", color: "#6b9eb8" },
    "SEARCH-DISSIPATING": { value: 2, label: "Search Dissipating", color: "#b3d4e5" },
    "CLEAR-DISSIPATION": { value: 1, label: "Clear Dissipation", color: "#d4e8f5" }
};

const TEMPORAL_PHASES = [
    "PRE-EXTRACTION", "ACTIVE-MOBILIZATION", "POST-DISPERSAL", 
    "RECOVERY-ATTEMPT", "SYSTEM-TRANSITION"
];

const FIVE_CRITERIA = [
    "CLOSURE-MATERIAL", "METABOLIC-EFFICIENCY", "TIMESCALE-BRIDGING",
    "PATTERN-PERSISTENCE", "SELF-RECOGNITION"
];

// Timeline entries with full codification
const entries = [
    // ===== DEEP TIME (DT) =====
    {
        id: 1,
        year: "4.5 billion years ago",
        sortKey: -4500000000,
        location: "Global",
        title: "Earth Formation",
        description: "Earth formation: Planetary accretion as primordial computation—gravity, heat, and chemical differentiation sorting materials into core, mantle, crust. Landscape intelligence begins with geological self-organisation.",
        keywords: ["accretion", "differentiation", "geological formation", "planetary origin", "self-organisation"],
        citation: "Hazen, R. M. (2012). The story of Earth: The first 4.5 billion years, from stardust to living planet. Viking.",
        category: "DT",
        source: "LI",
        sphereInterface: "LITHO-GEO",
        elementFunction: "ALL-CONCENTRATION",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 3 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: false,
        connections: [2, 3]
    },
    {
        id: 2,
        year: "3.8 billion years ago",
        sortKey: -3800000000,
        location: "Global",
        title: "First Life Emerges",
        description: "First life emerges: Biochemical computation begins—metabolism, replication, evolution. Living landscape processes information through molecular machinery. Order emerges at the edge of chaos.",
        keywords: ["abiogenesis", "metabolism", "molecular computation", "origin of life", "biochemistry"],
        citation: "Lane, N. (2015). The vital question: Energy, evolution, and the origins of complex life. W.W. Norton.",
        category: "DT",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "CARBON-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 5, timescale: 5, pattern: 5, recognition: 4 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: false,
        connections: [1, 3, 4]
    },
    {
        id: 3,
        year: "2.4 billion years ago",
        sortKey: -2400000000,
        location: "Global",
        title: "Great Oxidation Event",
        description: "Great Oxidation Event: Cyanobacteria compute atmospheric transformation—photosynthesis as planetary-scale chemical processing. Landscape intelligence rewrites Earth's chemistry.",
        keywords: ["oxygenation", "photosynthesis", "atmospheric change", "cyanobacteria", "biogeochemistry"],
        citation: "Knoll, A. H. (2003). Life on a young planet: The first three billion years of evolution on Earth. Princeton University Press.",
        category: "DT",
        source: "LI",
        sphereInterface: "BIO-ATMO",
        elementFunction: "OXYGEN-CYCLING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 4, metabolic: 5, timescale: 5, pattern: 5, recognition: 4 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: false,
        connections: [2, 4, 5]
    },
    {
        id: 4,
        year: "540 million years ago",
        sortKey: -540000000,
        location: "Global",
        title: "Cambrian Explosion",
        description: "Cambrian explosion: Evolutionary computation accelerates—body plans, sensory systems, predation feedback loops. Landscape intelligence diversifies through ecological interaction.",
        keywords: ["evolution", "biodiversity", "ecological interaction", "body plans", "sensory systems"],
        citation: "Erwin, D. H., & Valentine, J. W. (2013). The Cambrian explosion: The construction of animal biodiversity. Roberts and Company.",
        category: "DT",
        source: "LI",
        sphereInterface: "BIO-BIO",
        elementFunction: "BIOTA-DIVERSIFICATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 4, metabolic: 5, timescale: 5, pattern: 5, recognition: 4 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: false,
        connections: [3, 5, 6]
    },
    {
        id: 5,
        year: "350 million years ago",
        sortKey: -350000000,
        location: "Global",
        title: "Carboniferous Forests",
        description: "Carboniferous forests: Plant intelligence computes atmospheric carbon drawdown—coal formation as landscape memory storage. Deep time computation fossilised.",
        keywords: ["carbon sequestration", "coal formation", "forest intelligence", "atmospheric regulation", "deep time"],
        citation: "Beerling, D. (2007). The emerald planet: How plants changed Earth's history. Oxford University Press.",
        category: "DT",
        source: "LI",
        sphereInterface: "BIO-LITHO",
        elementFunction: "CARBON-SEQUESTRATION",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 4 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: false,
        connections: [4, 6, 36]
    },
    {
        id: 6,
        year: "252 million years ago",
        sortKey: -252000000,
        location: "Global",
        title: "Permian-Triassic Extinction",
        description: "Permian-Triassic extinction: Greatest mass extinction—landscape computation nearly collapses. 96% of marine species lost; planetary intelligence reboots.",
        keywords: ["mass extinction", "Permian", "collapse", "recovery", "planetary"],
        citation: "Benton, M. J. (2003). When life nearly died: The greatest mass extinction of all time. Thames & Hudson.",
        category: "DT",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "ALL-DISPERSION",
        indeterminacy: "CLEAR-DISSIPATION",
        fiveCriteria: { closure: 1, metabolic: 1, timescale: 3, pattern: 2, recognition: 3 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: false,
        connections: [5, 7]
    },
    {
        id: 7,
        year: "12,000 years ago",
        sortKey: -12000,
        location: "Global",
        title: "Holocene Begins",
        description: "Holocene begins: Stable climate enables agricultural computation—human landscape modification accelerates. Interglacial conditions as platform for civilisation.",
        keywords: ["Holocene", "agriculture", "stability", "civilisation", "interglacial"],
        citation: "Ruddiman, W. F. (2005). Plows, plagues, and petroleum: How humans took control of climate. Princeton University Press.",
        category: "DT",
        source: "LI",
        sphereInterface: "ATMO-TECHNO",
        elementFunction: "CARBON-MOBILIZATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 4, metabolic: 4, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [6, 8, 47]
    },

    // ===== INDIGENOUS EPISTEMOLOGIES (IE) =====
    {
        id: 8,
        year: "Continuous",
        sortKey: -10000,
        location: "Australia",
        title: "Aboriginal Australian Songlines",
        description: "Aboriginal Australian songlines: Country encoded with navigational algorithms, ecological knowledge, and kinship law. Walking activates landscape's memory; singing maintains its intelligence.",
        keywords: ["songlines", "navigation", "Country", "memory", "kinship"],
        citation: "Bradley, J. (2010). Singing saltwater country: Journey to the songlines of Carpentaria. Allen & Unwin.",
        category: "IE",
        source: "LI",
        sphereInterface: "BIO-TECHNO",
        elementFunction: "INFORMATION-MEMORY",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [9, 10, 11, 42]
    },
    {
        id: 9,
        year: "Continuous",
        sortKey: -10001,
        location: "Australia",
        title: "Aboriginal Fire Intelligence",
        description: "Aboriginal fire intelligence: Mosaic burning as landscape programming—fire-stick farming computes species succession, nutrient cycling, and habitat diversity across Country.",
        keywords: ["cultural burning", "fire management", "mosaic", "succession", "land management"],
        citation: "Gammage, B. (2011). The biggest estate on Earth: How Aborigines made Australia. Allen & Unwin.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-BIO",
        elementFunction: "FIRE-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [8, 10, 11]
    },
    {
        id: 10,
        year: "Continuous",
        sortKey: -10003,
        location: "Aotearoa/New Zealand",
        title: "Māori Whenua Intelligence",
        description: "Māori whenua intelligence: Land possesses mauri (life force) and whakapapa (genealogical computation). Mountains, rivers, forests are ancestors with agency and memory.",
        keywords: ["whenua", "mauri", "whakapapa", "genealogy", "life force"],
        citation: "Roberts, M., et al. (1995). Kaitiakitanga: Maori perspectives on conservation. Pacific Conservation Biology, 2(1), 7–20.",
        category: "IE",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "INFORMATION-MEMORY",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [8, 9, 11, 12]
    },
    {
        id: 11,
        year: "Continuous",
        sortKey: -10005,
        location: "Haudenosaunee Territory, North America",
        title: "Seventh Generation Thinking",
        description: "Haudenosaunee seventh generation thinking: Decision-making considers impacts seven generations forward—landscape intelligence computed across extended temporal horizons.",
        keywords: ["seventh generation", "temporal", "decision-making", "future", "Haudenosaunee"],
        citation: "Lyons, O. (1980). An Iroquois perspective. In C. Vecsey & R. W. Venables (Eds.), American Indian environments (pp. 171–174). Syracuse University Press.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-BIO",
        elementFunction: "INFORMATION-MEMORY",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [8, 10, 12, 13]
    },
    {
        id: 12,
        year: "Continuous",
        sortKey: -10006,
        location: "Hawai'i",
        title: "Hawaiian Ahupua'a",
        description: "Hawaiian ahupua'a: Watershed as computational unit—ridge to reef system integrating forest, agriculture, fishpond, ocean through water's flow and social kapu.",
        keywords: ["ahupua'a", "watershed", "integration", "kapu", "ridge-to-reef"],
        citation: "Minerbi, L. (1999). Indigenous management models and protection of the ahupua'a. Social Process in Hawaii, 39, 208–225.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-HYDRO",
        elementFunction: "WATER-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [11, 13, 14]
    },
    {
        id: 13,
        year: "Continuous",
        sortKey: -10007,
        location: "Amazonia",
        title: "Amazonian Terra Preta",
        description: "Amazonian terra preta: Anthropogenic dark earth as soil computing—biochar, organic matter, and microbiome engineered for fertility. Landscape memory in soil substrate.",
        keywords: ["terra preta", "soil engineering", "biochar", "carbon", "anthropogenic"],
        citation: "Lehmann, J., et al. (2003). Amazonian dark earths: Origin, properties, management. Springer.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-LITHO",
        elementFunction: "SOIL-MEMORY",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [12, 14, 15]
    },
    {
        id: 14,
        year: "Continuous",
        sortKey: -3000,
        location: "China",
        title: "Chinese Feng Shui",
        description: "Chinese feng shui: Landscape as energy field—qi flows computed through landform, water, orientation. Built environment as antenna tuned to landscape's intelligence.",
        keywords: ["feng shui", "qi", "landscape reading", "cosmology", "siting"],
        citation: "Bruun, O. (2008). An introduction to feng shui. Cambridge University Press.",
        category: "IE",
        source: "LI",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "ENERGY-SIGNALING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [13, 15, 16]
    },
    {
        id: 15,
        year: "Continuous",
        sortKey: -2500,
        location: "Persia/Iran",
        title: "Persian Qanat Systems",
        description: "Persian qanat systems: Underground aqueducts as landscape computation—gravity-fed irrigation computed through precise tunnel gradients across kilometres.",
        keywords: ["qanat", "irrigation", "groundwater", "gravity", "tunnel"],
        citation: "Beaumont, P. (1971). Qanat systems in Iran. Hydrological Sciences Bulletin, 16(1), 39–50.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-HYDRO",
        elementFunction: "WATER-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 4 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [14, 16, 12]
    },
    {
        id: 16,
        year: "Continuous",
        sortKey: -1000,
        location: "Bali, Indonesia",
        title: "Balinese Subak Water Temples",
        description: "Balinese subak water temples: Sacred irrigation as distributed computation—water allocation, pest control, and rice cultivation coordinated through ritual calendar.",
        keywords: ["subak", "irrigation", "temple", "water democracy", "rice"],
        citation: "Lansing, J. S. (1991). Priests and programmers: Technologies of power in the engineered landscape of Bali. Princeton University Press.",
        category: "IE",
        source: "LI",
        sphereInterface: "TECHNO-HYDRO",
        elementFunction: "WATER-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [15, 12, 14]
    },

    // ===== EARTH SYSTEM SCIENCE (ES) =====
    {
        id: 17,
        year: "1926",
        sortKey: 1926,
        location: "Russia",
        title: "Vernadsky's Biosphere",
        description: "Vernadsky's biosphere concept: Living matter as geological force—organisms compute planetary chemistry. Biosphere as thin computational layer transforming Earth.",
        keywords: ["biosphere", "Vernadsky", "living matter", "geochemistry", "planetary"],
        citation: "Vernadsky, V. I. (1998). The biosphere (D. B. Langmuir, Trans.). Copernicus. (Original work published 1926)",
        category: "ES",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "ALL-CONCENTRATION",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [18, 19, 21]
    },
    {
        id: 18,
        year: "1935",
        sortKey: 1935,
        location: "United Kingdom",
        title: "Tansley Coins 'Ecosystem'",
        description: "Tansley coins 'ecosystem': System concept applied to nature—organisms and environment as computational whole. Reductionism yields to emergent properties.",
        keywords: ["ecosystem", "Tansley", "systems", "ecology", "community"],
        citation: "Tansley, A. G. (1935). The use and abuse of vegetational concepts and terms. Ecology, 16(3), 284–307.",
        category: "ES",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "BIOTA-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 4, timescale: 4, pattern: 5, recognition: 4 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [17, 19, 20]
    },
    {
        id: 19,
        year: "1958",
        sortKey: 1958,
        location: "Mauna Loa, Hawai'i",
        title: "Keeling Curve Begins",
        description: "Keeling Curve begins: Continuous atmospheric CO2 monitoring—landscape intelligence made visible through data. Planetary metabolism tracked in real time.",
        keywords: ["CO2", "atmospheric monitoring", "Keeling", "climate", "baseline"],
        citation: "Keeling, C. D. (1960). The concentration and isotopic abundances of carbon dioxide in the atmosphere. Tellus, 12(2), 200–203.",
        category: "ES",
        source: "LI",
        sphereInterface: "ATMO-TECHNO",
        elementFunction: "CARBON-SIGNALING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 4, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: true,
        connections: [18, 20, 21, 28]
    },
    {
        id: 20,
        year: "1974",
        sortKey: 1974,
        location: "United Kingdom",
        title: "Gaia Hypothesis",
        description: "Lovelock and Margulis propose Gaia hypothesis: Earth as self-regulating system—biota and environment coupled in planetary-scale homeostatic computation.",
        keywords: ["Gaia", "Lovelock", "self-regulation", "homeostasis", "planetary"],
        citation: "Lovelock, J. E., & Margulis, L. (1974). Atmospheric homeostasis by and for the biosphere: The Gaia hypothesis. Tellus, 26(1–2), 2–10.",
        category: "ES",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "ALL-CONCENTRATION",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 5, metabolic: 5, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [17, 18, 19, 21, 43]
    },
    {
        id: 21,
        year: "1988",
        sortKey: 1988,
        location: "Global",
        title: "IPCC Established",
        description: "IPCC established: International Panel on Climate Change as institutional landscape intelligence—synthesising climate science for policy computation.",
        keywords: ["IPCC", "climate", "assessment", "international", "policy"],
        citation: "Houghton, J. T., Jenkins, G. J., & Ephraums, J. J. (Eds.). (1990). Climate change: The IPCC scientific assessment. Cambridge University Press.",
        category: "EG",
        source: "LI",
        sphereInterface: "TECHNO-ATMO",
        elementFunction: "CARBON-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [19, 20, 22, 34]
    },
    {
        id: 22,
        year: "2000",
        sortKey: 2000,
        location: "Global",
        title: "Crutzen Proposes Anthropocene",
        description: "Crutzen proposes Anthropocene: Human activity as geological computation—stratigraphy, chemistry, biology transformed at planetary scale.",
        keywords: ["Anthropocene", "Crutzen", "geological", "human impact", "stratigraphy"],
        citation: "Crutzen, P. J., & Stoermer, E. F. (2000). The \"Anthropocene.\" Global Change Newsletter, 41, 17–18.",
        category: "ES",
        source: "LI",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "ALL-MOBILIZATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 5, pattern: 4, recognition: 5 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: true,
        connections: [21, 23, 37, 47]
    },
    {
        id: 23,
        year: "2009",
        sortKey: 2009,
        location: "Global",
        title: "Planetary Boundaries Framework",
        description: "Planetary boundaries framework: Nine Earth system thresholds—climate, biodiversity, nitrogen, phosphorus. Landscape intelligence has limits; crossing triggers tipping cascades.",
        keywords: ["planetary boundaries", "thresholds", "safe operating space", "tipping points", "Earth system"],
        citation: "Rockström, J., et al. (2009). A safe operating space for humanity. Nature, 461(7263), 472–475.",
        category: "ES",
        source: "LI",
        sphereInterface: "BIO-GEO",
        elementFunction: "ALL-CYCLING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 5, pattern: 4, recognition: 5 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: true,
        connections: [20, 22, 37, 39]
    },

    // ===== CYBERNETICS & SYSTEMS (CS) =====
    {
        id: 24,
        year: "1961",
        sortKey: 1961,
        location: "Global",
        title: "Fuller's World Game",
        description: "\"Make the world work for 100% of humanity\"—planetary resource allocation through game/simulation. Students redistribute energy, population, industry; landscape intelligence as designable parameter.",
        keywords: ["Fuller", "World Game", "resources", "simulation", "planetary"],
        citation: "Fuller, R. B. (1969). Operating manual for spaceship Earth. Southern Illinois University Press.",
        category: "CS",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "ENERGY-CYCLING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [25, 26, 27]
    },
    {
        id: 25,
        year: "1968",
        sortKey: 1968,
        location: "Athens, Greece",
        title: "Doxiadis' Ekistics",
        description: "\"Science of human settlements\"—modelling cities and regions through computational analysis. Ekistic grid scales from room to ecumenopolis (world-city); proto-Earth system thinking applied to urbanisation.",
        keywords: ["Doxiadis", "ekistics", "settlements", "modelling", "scale"],
        citation: "Doxiadis, C. A. (1968). Ekistics: An introduction to the science of human settlements. Oxford University Press.",
        category: "CS",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "INFORMATION-MODELLING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [24, 26, 27]
    },

    // ===== LANDSCAPE ARCHITECTURE (LA) =====
    {
        id: 26,
        year: "1941",
        sortKey: 1941,
        location: "Atlantic Ocean",
        title: "Atlantic Charter: Planning the Planet",
        description: "Atlantic Charter: First moment of \"planning the planet\"—Roosevelt and Churchill establish framework for post-war international order. Sovereignty, territory, decolonisation computed through new institutions.",
        keywords: ["Atlantic Charter", "international", "sovereignty", "planning", "decolonisation"],
        citation: "Borgwardt, E. (2005). A new deal for the world: America's vision for human rights. Harvard University Press.",
        category: "LA",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [27, 28, 29]
    },
    {
        id: 27,
        year: "1928–1959",
        sortKey: 1945,
        location: "International",
        title: "Tyrwhitt and CIAM's International Apparatus",
        description: "Jacqueline Tyrwhitt organises modern architecture's planetary ambitions—translating Le Corbusier, coordinating CIAM congresses, connecting Doxiadis, Fuller, McLuhan. Architecture as computational infrastructure for international governance.",
        keywords: ["Tyrwhitt", "CIAM", "international", "modern architecture", "coordination"],
        citation: "Shoshkes, E. (2013). Jaqueline Tyrwhitt: A transnational life in urban planning and design. Routledge.",
        category: "LA",
        source: "TA",
        sphereInterface: "TECHNO-TECHNO",
        elementFunction: "INFORMATION-COORDINATION",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [24, 25, 26, 29]
    },
    {
        id: 28,
        year: "1958–present",
        sortKey: 1958.5,
        location: "Mauna Loa, Hawai'i",
        title: "Keeling Curve as Planetary Respiration",
        description: "Continuous CO2 measurement as planetary respiration made visible—\"the breathing of Gaia.\" Data reveals landscape intelligence operating at global scale; 64+ years of acceleration documented.",
        keywords: ["Keeling", "CO2", "respiration", "data", "acceleration"],
        citation: "Keeling, C. D. (1960). The concentration and isotopic abundances of carbon dioxide in the atmosphere. Tellus, 12(2), 200–203.",
        category: "ES",
        source: "TA",
        sphereInterface: "ATMO-BIO",
        elementFunction: "CARBON-SIGNALING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 4, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [19, 20, 21]
    },
    {
        id: 29,
        year: "1959",
        sortKey: 1959,
        location: "Otterlo, Netherlands",
        title: "CIAM X Habitat Debate",
        description: "Architecture splits over \"habitat\"—biological/ecological vs social/linguistic meanings. Team X challenges Athens Charter; moment where architecture chooses semantic ambiguity over planetary systems thinking.",
        keywords: ["CIAM", "habitat", "Team X", "Smithsons", "split"],
        citation: "Risselada, M., & van den Heuvel, D. (Eds.). (2005). Team 10: 1953–81, in search of a utopia of the present. NAi Publishers.",
        category: "LA",
        source: "TA",
        sphereInterface: "TECHNO-BIO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: false,
        connections: [27, 47, 48]
    },

    // ===== CRITICAL MATERIALS & EXTRACTION (CM) =====
    {
        id: 30,
        year: "1974",
        sortKey: 1974.1,
        location: "Global",
        title: "Wallerstein's World-Systems Analysis",
        description: "Global capitalism as integrated system—core, periphery, semi-periphery territories. Centre-periphery structures have duration; territorial computation of extraction and accumulation across 500 years.",
        keywords: ["Wallerstein", "world-systems", "core-periphery", "capitalism", "territory"],
        citation: "Wallerstein, I. (1974). The modern world-system I: Capitalist agriculture and the origins of the European world-economy in the sixteenth century. Academic Press.",
        category: "CM",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "ALL-MOBILIZATION",
        indeterminacy: "SEARCH-DISSIPATING",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 4, pattern: 5, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: true,
        connections: [31, 35, 36]
    },
    {
        id: 31,
        year: "1984",
        sortKey: 1984.1,
        location: "Japan",
        title: "NdFeB Magnet Discovery (Sumitomo)",
        description: "Sumitomo develops NdFeB permanent magnets: Neodymium-iron-boron magnets enable miniaturisation and efficiency gains—landscape intelligence embedded in material innovation.",
        keywords: ["NdFeB", "permanent magnet", "neodymium", "Sumitomo", "energy technology"],
        citation: "Sagawa, M., et al. (1984). New material for permanent magnets on a base of Nd and Fe. Journal of Applied Physics, 55(6), 2083–2087.",
        category: "CM",
        source: "JACO",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "NEODYMIUM-MOBILIZATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 4, timescale: 2, pattern: 5, recognition: 3 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [32, 35]
    },
    {
        id: 32,
        year: "1984",
        sortKey: 1984.2,
        location: "United States",
        title: "NdFeB Magnet Discovery (GM)",
        description: "General Motors simultaneously develops NdFeB magnets: Parallel innovation demonstrates convergent landscape intelligence in materials science.",
        keywords: ["NdFeB", "permanent magnet", "neodymium", "GM", "energy technology"],
        citation: "Croat, J. J., et al. (1984). Pr-Fe and Nd-Fe-based materials: A new class of high-performance permanent magnets. Journal of Applied Physics, 55(6), 2078–2082.",
        category: "CM",
        source: "JACO",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "NEODYMIUM-MOBILIZATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 4, timescale: 2, pattern: 5, recognition: 3 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [31, 35]
    },
    {
        id: 33,
        year: "Continuous",
        sortKey: 1986.5,
        location: "Chernobyl / Global",
        title: "Radioactive Half-life as Temporal Frame",
        description: "Thinking \"long-term\" through radioactive decay—materials with half-lives of thousands of years. Chernobyl radionuclides passed from mother to child; landscape intelligence includes nuclear contamination as permanent marker.",
        keywords: ["half-life", "radioactive", "temporal", "Chernobyl", "contamination"],
        citation: "Alexievich, S. (2006). Voices from Chernobyl: The oral history of a nuclear disaster (K. Gessen, Trans.). Picador.",
        category: "CM",
        source: "TA",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "ALL-DISPERSION",
        indeterminacy: "CLEAR-DISSIPATION",
        fiveCriteria: { closure: 1, metabolic: 1, timescale: 5, pattern: 4, recognition: 4 },
        temporalPhase: "POST-DISPERSAL",
        isAnchor: false,
        connections: [38, 39]
    },
    {
        id: 34,
        year: "1988–present",
        sortKey: 1988.5,
        location: "Global",
        title: "IPCC as Planetary Bureaucracy",
        description: "IPCC as \"location of planning the planet\"—industrial understanding of industrial destruction. Computational modelling requires supercomputers consuming town-scale energy; governance through scenarios.",
        keywords: ["IPCC", "bureaucracy", "modelling", "scenarios", "governance"],
        citation: "Edwards, P. N. (2010). A vast machine: Computer models, climate data, and the politics of global warming. MIT Press.",
        category: "EG",
        source: "TA",
        sphereInterface: "TECHNO-ATMO",
        elementFunction: "CARBON-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 5 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [21, 43]
    },
    {
        id: 35,
        year: "2010",
        sortKey: 2010,
        location: "China / Japan",
        title: "China REE Export Restrictions",
        description: "China restricts rare earth exports during Senkaku dispute: Landscape intelligence becomes geopolitical weapon—critical minerals as strategic leverage.",
        keywords: ["REE", "export restrictions", "supply chain", "geopolitics", "critical minerals"],
        citation: "Bradsher, K. (2010, September 22). Amid tension, China blocks vital exports to Japan. The New York Times.",
        category: "CM",
        source: "JACO",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "ALL-CONCENTRATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [31, 32, 36]
    },
    {
        id: 36,
        year: "2011",
        sortKey: 2011.1,
        location: "Global",
        title: "Mitchell's Carbon Democracy",
        description: "Oil doesn't just fuel economies—it shapes political possibilities. Coal required mass labour (enabling strikes/democracy); oil's flow-based logistics enables autocracy. Energy systems compute political forms.",
        keywords: ["Mitchell", "carbon democracy", "oil", "politics", "energy"],
        citation: "Mitchell, T. (2011). Carbon democracy: Political power in the age of oil. Verso.",
        category: "CM",
        source: "TA",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "CARBON-MOBILIZATION",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 4, pattern: 5, recognition: 5 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: true,
        connections: [30, 5, 51]
    },
    {
        id: 37,
        year: "2013",
        sortKey: 2013.1,
        location: "Global",
        title: "Stranded Assets Concept",
        description: "Unburnable carbon—oil reserves that cannot be extracted if climate targets met. Buildings, pension funds, stock exchanges invested in stranded assets; global economy as computation of future extraction that cannot occur.",
        keywords: ["stranded assets", "carbon bubble", "finance", "unburnable", "risk"],
        citation: "Carbon Tracker Initiative. (2013). Unburnable carbon 2013: Wasted capital and stranded assets.",
        category: "CM",
        source: "TA",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "CARBON-CONCENTRATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [36, 23]
    },

    // ===== CONTEMPORARY THEORY (CT) =====
    {
        id: 38,
        year: "2013",
        sortKey: 2013.2,
        location: "Global",
        title: "Territory as Terror",
        description: "Territory not from terra (land) but from terrere (to frighten)—warning others from what sustains you. Geo-semantics of landscape intelligence includes multi-species territorial marking; borders as survival computation.",
        keywords: ["territory", "terror", "etymology", "survival", "borders"],
        citation: "Elden, S. (2013). The birth of territory. University of Chicago Press.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "INFORMATION-MEMORY",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 4, pattern: 5, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [39, 44]
    },
    {
        id: 39,
        year: "2014",
        sortKey: 2014.1,
        location: "Global",
        title: "Haff's Technosphere",
        description: "Technosphere as planetary-scale entity—30 trillion tons of human-made stuff, self-organising like atmosphere or biosphere. Humans are components, not controllers; landscape intelligence includes technological systems now operating autonomously.",
        keywords: ["technosphere", "Haff", "self-organisation", "planetary", "mass"],
        citation: "Haff, P. K. (2014). Humans and technology in the Anthropocene: Six rules. The Anthropocene Review, 1(2), 126–136.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "ALL-MOBILIZATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 3, metabolic: 2, timescale: 4, pattern: 5, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: true,
        connections: [22, 40, 41]
    },
    {
        id: 40,
        year: "2014",
        sortKey: 2014.2,
        location: "Baltic Sea",
        title: "Baltic Dead Zone",
        description: "Baltic Sea as world's second-largest dead zone—agricultural runoff (petrochemical fertilisers) creates algal blooms, oxygen depletion. Landscape intelligence collapsed through anthropogenic biogeochemical cycle disruption.",
        keywords: ["Baltic", "dead zone", "eutrophication", "fertiliser", "anoxic"],
        citation: "Carstensen, J., Andersen, J. H., Gustafsson, B. G., & Conley, D. J. (2014). Deoxygenation of the Baltic Sea during the last century. PNAS, 111(15), 5628–5633.",
        category: "EG",
        source: "TA",
        sphereInterface: "HYDRO-TECHNO",
        elementFunction: "ALL-DISPERSION",
        indeterminacy: "CLEAR-DISSIPATION",
        fiveCriteria: { closure: 1, metabolic: 1, timescale: 3, pattern: 3, recognition: 4 },
        temporalPhase: "POST-DISPERSAL",
        isAnchor: false,
        connections: [39, 41, 23]
    },
    {
        id: 41,
        year: "2014",
        sortKey: 2014.3,
        location: "Global",
        title: "Technosphere's Non-recycling",
        description: "Forests don't drown in leaves—they recycle. The 30-trillion-ton technosphere doesn't recycle; debris accumulates as carbon in atmosphere, plastic in oceans, rubble in landscapes. Metabolic failure at planetary scale.",
        keywords: ["recycling", "technosphere", "debris", "accumulation", "metabolism"],
        citation: "Haff, P. K. (2014). Technology as a geological phenomenon. Geological Society, London, Special Publications, 395(1), 301–309.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "ALL-DISPERSION",
        indeterminacy: "CLEAR-DISSIPATION",
        fiveCriteria: { closure: 1, metabolic: 1, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [39, 40]
    },
    {
        id: 42,
        year: "2017",
        sortKey: 2017.1,
        location: "Global",
        title: "Multispecies Sensing",
        description: "\"Technology sensing us\"—plants, fungi, bacteria, viruses all sense. Landscape intelligence distributed across sensing species; COVID-19 demonstrates viral computation. Human sensing is not privileged.",
        keywords: ["sensing", "multispecies", "plants", "fungi", "virus"],
        citation: "Gagliano, M., Ryan, J. C., & Vieira, P. (Eds.). (2017). The language of plants: Science, philosophy, literature. University of Minnesota Press.",
        category: "CT",
        source: "TA",
        sphereInterface: "BIO-TECHNO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 4, metabolic: 4, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "PRE-EXTRACTION",
        isAnchor: true,
        connections: [8, 10, 20]
    },
    {
        id: 43,
        year: "2015",
        sortKey: 2015.1,
        location: "Global",
        title: "Data Incompatibility Crisis",
        description: "No \"open data\" in science—only open access data with declared purpose. Ocean data scattered across hundreds of institutions; formats incompatible; military dominates. Landscape intelligence fragmented across incommensurate datasets.",
        keywords: ["data", "incompatibility", "open access", "institutions", "fragmentation"],
        citation: "Borgman, C. L. (2015). Big data, little data, no data: Scholarship in the networked world. MIT Press.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-TECHNO",
        elementFunction: "INFORMATION-DISPERSION",
        indeterminacy: "SEARCH-DISSIPATING",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 3, pattern: 3, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [34, 44]
    },
    {
        id: 44,
        year: "2018",
        sortKey: 2018.1,
        location: "Global",
        title: "Imaginal Technologies",
        description: "Borders formed not just by laws, protocols, algorithms—but by images, perception, ways of seeing. Remote sensing, thermal cameras, satellite imagery as extractive images that also enable counter-uses.",
        keywords: ["imaginal", "borders", "perception", "remote sensing", "extraction"],
        citation: "Palmesino, J., & Rönnskog, A.-S. (2018). Oceans in transformation. e-flux architecture.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-TECHNO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [38, 43, 45]
    },
    {
        id: 45,
        year: "2018",
        sortKey: 2018.2,
        location: "Global",
        title: "Deficit Model of Activism Critique",
        description: "\"If only you would feel what I feel, you would change\"—activism as filling knowledge/empathy deficit. Structures of violence now below state (corporations) and above (international law). Proximity to form-generating structures required.",
        keywords: ["activism", "deficit model", "proximity", "structures", "transformation"],
        citation: "Latour, B. (2018). Down to Earth: Politics in the new climatic regime (C. Porter, Trans.). Polity.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-TECHNO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 2, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [44, 46]
    },
    {
        id: 46,
        year: "2018",
        sortKey: 2018.3,
        location: "Global",
        title: "Poly-creativity vs Single Author",
        description: "\"No master, no maestro\"—polyphony of solutions replacing single-author design. Architecture education challenged by need for multiple, distributed, collaborative responses; Gaia as self-organising without central subject.",
        keywords: ["poly-creativity", "polyphony", "collaboration", "authorship", "distributed"],
        citation: "Stengers, I. (2018). Another science is possible: A manifesto for slow science. Polity.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-BIO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [20, 45, 48]
    },
    {
        id: 47,
        year: "2019",
        sortKey: 2019.1,
        location: "Global Coastal",
        title: "Sensible Zone Concept",
        description: "200m above and below sea level—zone of photosynthesis, coastal urbanisation, extraction, and vulnerability. Where landscape intelligence is most concentrated and most threatened; site of necessary retreat.",
        keywords: ["sensible zone", "coastal", "vulnerability", "extraction", "retreat"],
        citation: "Territorial Agency. (2020). Oceans in transformation. TBA21–Academy.",
        category: "CT",
        source: "TA",
        sphereInterface: "BIO-TECHNO",
        elementFunction: "ALL-CYCLING",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 3, metabolic: 4, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "ACTIVE-MOBILIZATION",
        isAnchor: false,
        connections: [7, 22, 48]
    },
    {
        id: 48,
        year: "2020",
        sortKey: 2020.1,
        location: "Global",
        title: "Architecture as Holocene Practice",
        description: "Architecture developed during 11,000-year interglacial stability—bricks from fluvial clay, monuments aligned to stable plains. Same fluvial valleys now sites of war. Anthropocene destabilises architecture's foundation.",
        keywords: ["Holocene", "stability", "fluvial", "bricks", "war"],
        citation: "Palmesino, J. (2020). Plan the Planet. AA School.",
        category: "LA",
        source: "TA",
        sphereInterface: "TECHNO-LITHO",
        elementFunction: "ALL-CONCENTRATION",
        indeterminacy: "PHASE-TRANSITION",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 3, pattern: 4, recognition: 4 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: false,
        connections: [7, 29, 47, 49]
    },
    {
        id: 49,
        year: "2020",
        sortKey: 2020.2,
        location: "Global",
        title: "Image as Diplomatic Space",
        description: "When scientists see their data visualised together, they stop speaking as experts and begin negotiating. Images create space where \"you have to build together what you want to discuss\"—without pre-stated agreement.",
        keywords: ["image", "diplomacy", "negotiation", "visualisation", "agreement"],
        citation: "Latour, B. (2004). Why has critique run out of steam? Critical Inquiry, 30(2), 225–248.",
        category: "CT",
        source: "TA",
        sphereInterface: "TECHNO-TECHNO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 4, pattern: 4, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [44, 48, 50]
    },
    {
        id: 50,
        year: "2017",
        sortKey: 2017.2,
        location: "Coastal Global",
        title: "Retreat as Design Problem",
        description: "\"We don't have intellectual capacity to withdraw\"—humans have never had to step back. Sea level rise requires retreat from coastal cities; architecture conceived as construction not dismantlement. Design for withdrawal unprecedented.",
        keywords: ["retreat", "withdrawal", "sea level", "coastal", "design"],
        citation: "Hino, M., Field, C. B., & Mach, K. J. (2017). Managed retreat as a response to natural hazard risk. Nature Climate Change, 7(5), 364–370.",
        category: "EG",
        source: "TA",
        sphereInterface: "TECHNO-GEO",
        elementFunction: "INFORMATION-SIGNALING",
        indeterminacy: "SEARCH-PROMISING",
        fiveCriteria: { closure: 2, metabolic: 2, timescale: 4, pattern: 3, recognition: 4 },
        temporalPhase: "RECOVERY-ATTEMPT",
        isAnchor: false,
        connections: [47, 48]
    },
    {
        id: 51,
        year: "2021",
        sortKey: 2021.1,
        location: "Global",
        title: "Energy-Polity Coupling",
        description: "Each energy regime produces corresponding political architecture—wood/city-state, coal/empire-nation-parliament, oil/international, gas/global, renewables/cosmopolitical. Energy transition requires political transition.",
        keywords: ["energy", "polity", "transition", "coal", "oil"],
        citation: "Territorial Agency. (2021). Museum of Oil. Sternberg Press.",
        category: "CM",
        source: "TA",
        sphereInterface: "LITHO-TECHNO",
        elementFunction: "ENERGY-CYCLING",
        indeterminacy: "CLEAR-COHERENT",
        fiveCriteria: { closure: 3, metabolic: 3, timescale: 5, pattern: 5, recognition: 5 },
        temporalPhase: "SYSTEM-TRANSITION",
        isAnchor: true,
        connections: [36, 30]
    }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { entries, CATEGORIES, SOURCES, SPHERE_INTERFACES, ELEMENT_FUNCTIONS, INDETERMINACY_POSITIONS, TEMPORAL_PHASES, FIVE_CRITERIA };
}
